### ISSUE TITLE
Area51Logic.dll is detected a virus by many anti-viruses

### ISSUE THREAD

**Issue by RADIOACTIVEshrek** [ProjectDreamland/game#13]
https://www.virustotal.com/gui/file/99e0f6f960adc8c0ea3da2b3d677bafb8783a63388f87bdff205864dcb121a26
Why is it detected as a virus by so many anti-viruses?

**Comment by SilentMRG** [comment]
![false-positives-false-7ac7340698](https://github.com/ProjectDreamland/game/assets/62117728/b5432b39-4065-46ef-83f5-05ee04c1477f)

**Comment by andrewmd5** [comment]
Bro, I don’t know. Stop using anti viruses.
