### ISSUE TITLE
Trojan Included in release 1.1

### ISSUE THREAD

**Issue by VulpusMaximus** [ProjectDreamland/game#3]
I had found this on ModDB and downloaded it there, ran it and Bitdefender claimed there was a trojan. On a different computer, that hasn't had this before, I downloaded the 1.1 release from this repo, scanned the Game.zip with Bitdefender, and the scan showed a trojan was in the zip 
![image](https://user-images.githubusercontent.com/37087082/42729734-b59e7966-87af-11e8-98c4-0da154828e74.png)

**Comment by andrewmd5** [comment]
Anti-viruses being unreliable as always.
